### ISSUE TITLE
mysql_log_path/file should not be checked

### ISSUE THREAD

**Issue by rndmh3ro** [dev-sec/mysql-baseline#33]
The following is defined:
```
 mysql_log_path = '/var/log/'
```
and checked here:
```
describe file(mysql_log_path) do
  it { should be_directory }
  it { should be_owned_by 'root' }
  it { should be_grouped_into mysql_log_dir_group }
end
```

However I do not think, this should be part of the mysql-baseline (more likely part of the linux-baseline), because that directory is not part of a mysql-installation.

Furthermore I don't know if we should check for the mysql-logfile at all. Its path is different on many systems. 
An idea would be to read the path from the configuration and then check its permissions and owner.

**Comment by chris-rock** [comment]
@atomic111 Can you help here?

**Comment by atomic111** [comment]
@rndmh3ro yes we can include this in the linux-baseline. then we have to change this test a bit. Can you please create a PR for this in the linux-baseline?
