### ISSUE TITLE
CentOS 7 and 8 logfile is /var/log/mariadb/mariadb.log

### ISSUE THREAD

**Issue by rndmh3ro** [dev-sec/mysql-baseline#50]
**Describe the bug**

Running the baseline on CentOS 7 and CentOS 8 fails with this error:
```
              ×  mysql-conf-06: ensure log file is owned by mysql user (2 failed),
                 ×  File /var/log//mysqld.log is expected to be owned by \"mysql\",
                 expected `File /var/log//mysqld.log.owned_by?(\"mysql\")` to return true, got false,
                 ×  File /var/log//mysqld.log is expected to be grouped into \"mysql\",
```

The reason is that Mariadb is installed by default and has different logfile-paths and names.

**Expected behavior**
The test should look for mariadb:

```
[root@instance /]# ls -lsah /var/log/mariadb/mariadb.log
4.0K -rw-r----- 1 mysql mysql 1.9K Aug  5 10:06 /var/log/mariadb/mariadb.log
```

**OS / Environment**

CentOS7 and 8

**Baseline Version**
master

**Comment by micheelengronne** [comment]
Related: https://github.com/dev-sec/mysql-baseline/pull/51

**Comment by micheelengronne** [comment]
It is available in https://github.com/dev-sec/mysql-baseline/releases/tag/3.1.5
