### ISSUE TITLE
Dynamically determine logfile path

### ISSUE THREAD

**Issue by rndmh3ro** [dev-sec/mysql-baseline#53]
**Is your feature request related to a problem? Please describe.**
The logfile-paths in the mysql_conf control (https://github.com/dev-sec/mysql-baseline/blob/master/controls/mysql_conf.rb#L27-L28) are different on all the operating systems: centos differs from ubuntu 18.04 which differ from ubuntu 20.04 and so on.

Hard-coding these is error prone and tedious.

**Describe the solution you'd like**
I'd like to dynamically fetch the paths from mysql.
There are two good ways I know of:

* use inspec to fetch the path:
```
inspec> mysql_conf.params.mysqld.log_error
=> "/var/log/mysql/error.log"
```

* use sql:
```
root@instance:/# mysql -sN -e 'select @@log_error';
/var/log/mysql/error.log

root@instance:/# mysql -sN -e 'show global variables like "log_error"';
log_error       /var/log/mysql/error.log
```

What do you think about this idea and which approach do you like better?

**Comment by micheelengronne** [comment]
I would prefer the Inspec approach over the sql approach as it is more agnostic on the system state.

**Comment by rndmh3ro** [comment]
The SQL approach has also the benefit that it gets the currently used directory, not only the directory that is set in the config file.

**Comment by micheelengronne** [comment]
That reinforces the advantage of Inspec. If there is a difference between the used directory and the one set in the config file, an alert should be triggered, no ?

**Comment by micheelengronne** [comment]
But, for instance, imagine a system where even `root@localhost` does not have a passwordless access on the SQL engine, the check would break if SQL is used.

**Comment by chris-rock** [comment]
Essentially you could argue that both need to be checked. In a first run, I think we should stick with the inspec path way. Too many things can go wrong with the sql query.

**Comment by rndmh3ro** [comment]
> But, for instance, imagine a system where even root@localhost does not have a passwordless access on the SQL engine, the check would break if SQL is used.

The baseline already uses SQL-checks extensively with password-login, so I see no problem here.

I agree on using inspec. I'll implement it.

**Comment by rndmh3ro** [comment]
One problem with using the inspec way is that the path has to be defined in the configuration-file. If it is not defined, inspec doesn't know about it. 
So if one uses a default configuration where the log-directory is not explicetly defined, the check will fail hard.

That's why I implemented a simple if-else condition to firs tcheck with inspec and when this fails, check with sql.

https://github.com/dev-sec/mysql-baseline/pull/54

**Comment by rndmh3ro** [comment]
Can anyone help me with the failing travis build? https://travis-ci.org/github/dev-sec/mysql-baseline/builds/716598852

```
mysql_data_path = if mysql_conf.params.mysqld.datadir
                  else
                    command("mysql -u#{user} -p#{pass} -sN -e \"select @@GLOBAL.datadir\";").stdout.strip
                  end
```

rubocop fails, because `mysql_conf.params.mysqld.datadir` is empty.:

```
NoMethodError: undefined method `datadir' for nil:NilClass
./controls/mysql_conf.rb:26:in `load_with_context'
/home/basti/os-hardening/mysql-baseline/Rakefile:26:in `block (2 levels) in <top (required)>'
/home/basti/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/home/basti/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/home/basti/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/home/basti/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/home/basti/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/basti/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/basti/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/home/basti/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/home/basti/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/home/basti/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/home/basti/.gem/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/home/basti/.gem/ruby/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/home/basti/.gem/ruby/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/bin/bundle:23:in `load'
/bin/bundle:23:in `<main>'
Tasks: TOP => default => test:check
(See full trace by running task with --trace)
```

This does not fail, however rubocop complains:

```
if mysql_conf.params.mysqld.datadir
  mysql_data_path = mysql_conf.params.mysqld.datadir
else
  mysql_data_path = command("mysql -u#{user} -p#{pass} -sN -e \"select @@GLOBAL.datadir\";").stdout.strip
end
```

```
controls/mysql_conf.rb:25:1: C: Style/ConditionalAssignment: Use the return of the conditional for variable assignment and comparison.
if mysql_conf.params.mysqld.datadir ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

However both work with inspec.

**Comment by micheelengronne** [comment]
I think you have to repeat `mysql_conf.params.mysqld.datadir` inside the conditional.

```
mysql_data_path = if mysql_conf.params.mysqld.datadir
                                 mysql_conf.params.mysqld.datadir
                               else
                                 command("mysql -u#{user} -p#{pass} -sN -e \"select @@GLOBAL.datadir\";").stdout.strip
                               end
```

**Comment by micheelengronne** [comment]
Or perhaps a ternary operator ?

```
mysql_data_path = defined?(mysql_conf.params.mysqld.datadir) ? mysql_conf.params.mysqld.datadir : command("mysql -u#{user} -p#{pass} -sN -e \"select @@GLOBAL.datadir\";").stdout.strip
```

**Comment by rndmh3ro** [comment]
Thanks!

```
mysql_data_path = defined?(mysql_conf.params.mysqld.datadir) ? mysql_conf.params.mysqld.datadir : command("mysql -u#{user} -p#{pass} -sN -e \"select @@GLOBAL.datadir\";").stdout.strip
mysql_log_file = defined?(mysql_conf.params.mysqld.log_error) ? mysql_conf.params.mysqld.log_error : command("mysql -u#{user} -p#{pass} -sN -e \"select @@GLOBAL.log_error\";").stdout.strip
```
This works with rubocop, however the assignment here is then wrong:

```
mysql_conf.params.mysqld.log_error: "/var/log/mysql/error.log"
mysql_log_file: "stderr"
```

I tried this:
```
mysql_data_path = mysql_conf.params.mysqld.datadir.respond_to?(:to_str) ? mysql_conf.params.mysqld.datadir : command("mysql -u#{user} -p#{pass} -sN -e \"select @@GLOBAL.datadir\";").stdout.strip
mysql_log_file = mysql_conf.params.mysqld.log_error.respond_to?(:to_str) ? mysql_conf.params.mysqld.log_error : command("mysql -u#{user} -p#{pass} -sN -e \"select @@GLOBAL.log_error\";").stdout.strip
```

It fails in rubocop but not in inspec:

```
NoMethodError: undefined method `datadir' for nil:NilClass
```

This fails in rubocop but not in inspec:
```
mysql_data_path = (mysql_conf.params.mysqld.datadir).respond_to?(:to_str) ? mysql_conf.params.mysqld.datadir : command("mysql -u#{user} -p#{pass} -sN -e \"select @@GLOBAL.datadir\";").stdout.strip
mysql_log_file = (mysql_conf.params.mysqld.log_error).respond_to?(:to_str) ? mysql_conf.params.mysqld.log_error : command("mysql -u#{user} -p#{pass} -sN -e \"select @@GLOBAL.log_error\";").stdout.strip
```

```
controls/mysql_conf.rb:25:19: C: Style/RedundantParentheses: Don't use parentheses around a method call.
mysql_data_path = (mysql_conf.params.mysqld.datadir).respond_to?(:to_str) ? mysql_conf.params.mysqld.datadir : command("mysql -u#{user} -p#{pass} -sN -e \"select @@GLOBAL.datadir\";").stdout.strip
```


I'm at loss. :(

**Comment by micheelengronne** [comment]
* In the first case, maybe replace `defined?(mysql_conf.params.mysqld.datadir)` with `!mysql_conf.params.mysqld.datadir.nil?`. `defined?` does not return a boolean but the value or nil, so it may mess with the check.

* In the second case, the error may be due to the fact that `mysql_conf.params.mysqld` itself is not defined. It may be necessary to check its existence before checking `mysql_conf.params.mysqld.datadir` existence.

* In the third case, the parenthesis around `(mysql_conf.params.mysqld.datadir)` are useless so rubocop fails. Removing them fails back to the second case.

**Comment by rndmh3ro** [comment]
I think I finally did it right.

Thank you for your help @micheelengronne!

**Comment by rndmh3ro** [comment]
fixed by https://github.com/dev-sec/mysql-baseline/pull/54
